name: bitcoin_clock
description: Bitcoin Clock
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  fullscreen: ^1.0.3
  widget_mask: ^1.0.0+0

  # State management
  stacked: ^3.0.0
  stacked_themes: ^0.3.9

  # Services
  intl: ^0.17.0
  http: ^0.13.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  # App images
  assets:
    - assets/images/logo.png
  
  # Custom fonts
  fonts:
    - family: Economica
      fonts:
        - asset: assets/fonts/Economica-Regular.ttf
        - asset: assets/fonts/Economica-Italic.ttf
          style: italic
        - asset: assets/fonts/Economica-Bold.ttf
          weight: 700
        - asset: assets/fonts/Economica-BoldItalic.ttf
          weight: 700
          style: italic
